### ISSUE TITLE
et -i fs.js:904   return binding.readdir(pathModule._makeLong(path), options.encoding);

### ISSUE THREAD

**Issue by lgXenos** [ElementUI/theme-chalk#15]
Hi 
I'm try install custom theme as in doc: http://element.eleme.io/#/en-US/component/custom-theme

But have unexpected error
:(

`$ et -i
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/usr/lib/node_modules/element-theme/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/usr/lib/node_modules/element-theme/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/usr/lib/node_modules/element-theme/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/lib/node_modules/element-theme/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/lib/node_modules/element-theme/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/lib/node_modules/element-theme/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/lib/node_modules/element-theme/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)`

**Comment by JoshyJonesX** [comment]
check if your folder structure is nested correctly....fixed mine
