### ISSUE TITLE
postcss-loader failed to load index.css in Nuxt.js 2.2.0

### ISSUE THREAD

**Issue by Druson** [ElementUI/theme-chalk#20]
Put `import 'element-ui/lib/theme-chalk/index.css'` in a vue page, failed to load 'element-ui/lib/theme-chalk/index.css' in Nuxt.js 2.2.0  with below error when run `npm run generate`:
```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'search' of undefined
    at D:\mynuxtproject\node_modules\element-ui\lib\theme-chalk\index.css:10194:1
    at isValueCustomProp (D:\mynuxtproject\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:106:45)
    at D:\mynuxtproject\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:449:18
    at mergeRules (D:\mynuxtproject\node_modules\postcss-merge-longhand\dist\lib\mergeRules.js:46:17)
    at wsc.forEach (D:\mynuxtproject\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:438:34)
    at Array.forEach (<anonymous>)
    at Object.merge (D:\mynuxtproject\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:436:9)
    at _decl2.default.forEach.p (D:\mynuxtproject\node_modules\postcss-merge-longhand\dist\index.js:22:19)
    at Array.forEach (<anonymous>)
    at css.walkRules.rule (D:\mynuxtproject\node_modules\postcss-merge-longhand\dist\index.js:20:28)
    at D:\mynuxtproject\node_modules\postcss\lib\container.js:239:18
    at D:\mynuxtproject\node_modules\postcss\lib\container.js:135:18
    at Root.each (D:\mynuxtproject\node_modules\postcss\lib\container.js:101:16)
    at Root.walk (D:\mynuxtproject\node_modules\postcss\lib\container.js:131:17)
    at Root.walkRules (D:\mynuxtproject\node_modules\postcss\lib\container.js:237:19)
    at css (D:\mynuxtproject\node_modules\postcss-merge-longhand\dist\index.js:19:13)
    at initializePlugin (D:\mynuxtproject\node_modules\cssnano\dist\index.js:35:51)
 @ ./node_modules/element-ui/lib/theme-chalk/index.css 4:14-190
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/mallmb.vue?vue&type=script&lang=js&
 @ ./layouts/mallmb.vue?vue&type=script&lang=js&
 @ ./layouts/mallmb.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js
× fatal Nuxt Build Error
```
No error after change `.el-step__icon.is-text{border-radius:50%;border:2px solid;border-color:inherit}` to `.el-step__icon.is-text{border-radius:50%;border-color:inherit;border:2px solid;}` or `.el-step__icon.is-text{border-radius:50%;border:2px solid inherit}`

**Comment by Undrum** [comment]
The problem is here: https://github.com/ElementUI/theme-chalk/blob/1235508e767e9afc873feb05e4cdecf2f769c047/src/step.scss#L70
